POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Vídeo de teste",
    "description": "Apenas algum teste",
    "duration": 180
}


###

GET  http://localhost:3333/videos


###

PUT http://localhost:3333/videos/adc62e5b-398d-4ebf-8590-2e9143838439
Content-Type: application/json

{
    "title": "Vídeo de teste2",
    "description": "Apenas algum teste",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/adc62e5b-398d-4ebf-8590-2e9143838439

